//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : ROSE
//  @ File Name : InferLocalPathologyROSE.h
//  @ Date : 2019/8/15
//  @ Author : weiping liu
//
//


#if !defined(_INFERLOCALPATHOLOGYROSE_H)
#define _INFERLOCALPATHOLOGYROSE_H

#include "InferLocalBase.h"
#include "IFPipelinePathologyROSEOut.h"
#include "AIThread.h"

#include <opencv2/opencv.hpp>
#include <opencv2/imgproc.hpp>

#include "tensorflow/cc/ops/image_ops.h"
#include "tensorflow/cc/ops/standard_ops.h"
#include "tensorflow/core/framework/graph.pb.h"
#include "tensorflow/core/framework/tensor.h"
#include "tensorflow/core/graph/default_device.h"
#include "tensorflow/core/graph/graph_def_builder.h"
#include "tensorflow/core/platform/logging.h"
#include "tensorflow/core/platform/types.h"
#include "tensorflow/core/public/session.h"


namespace ALPHA
{
	namespace ROSE
	{
		class InferLocalPathologyROSE : public COMM::InferLocalBase 
		{
		public:
			explicit InferLocalPathologyROSE() {}
			~InferLocalPathologyROSE() {}

			COMM::DataObj* predict(COMM::DataObj* dataObj, const std::string& modelName) override;
		};
	}
}


#endif  //_INFERLOCALPATHOLOGYROSE_H
