
#ifndef PIPELINEPATHOLOGYROSEFACTORY_EXPORT_H
#define PIPELINEPATHOLOGYROSEFACTORY_EXPORT_H

#ifdef PIPELINEPATHOLOGYROSEFACTORY_STATIC_DEFINE
#  define PIPELINEPATHOLOGYROSEFACTORY_EXPORT
#  define PIPELINEPATHOLOGYROSEFACTORY_NO_EXPORT
#else
#  ifndef PIPELINEPATHOLOGYROSEFACTORY_EXPORT
#    ifdef PipelinePathologyROSEFactory_EXPORTS
        /* We are building this library */
#      define PIPELINEPATHOLOGYROSEFACTORY_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define PIPELINEPATHOLOGYROSEFACTORY_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef PIPELINEPATHOLOGYROSEFACTORY_NO_EXPORT
#    define PIPELINEPATHOLOGYROSEFACTORY_NO_EXPORT 
#  endif
#endif

#ifndef PIPELINEPATHOLOGYROSEFACTORY_DEPRECATED
#  define PIPELINEPATHOLOGYROSEFACTORY_DEPRECATED __declspec(deprecated)
#endif

#ifndef PIPELINEPATHOLOGYROSEFACTORY_DEPRECATED_EXPORT
#  define PIPELINEPATHOLOGYROSEFACTORY_DEPRECATED_EXPORT PIPELINEPATHOLOGYROSEFACTORY_EXPORT PIPELINEPATHOLOGYROSEFACTORY_DEPRECATED
#endif

#ifndef PIPELINEPATHOLOGYROSEFACTORY_DEPRECATED_NO_EXPORT
#  define PIPELINEPATHOLOGYROSEFACTORY_DEPRECATED_NO_EXPORT PIPELINEPATHOLOGYROSEFACTORY_NO_EXPORT PIPELINEPATHOLOGYROSEFACTORY_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef PIPELINEPATHOLOGYROSEFACTORY_NO_DEPRECATED
#    define PIPELINEPATHOLOGYROSEFACTORY_NO_DEPRECATED
#  endif
#endif

#endif /* PIPELINEPATHOLOGYROSEFACTORY_EXPORT_H */
