//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : VIRUS
//  @ File Name : PipelinePathologyVIRUSFactory.h
//  @ Date : 2019/8/15
//  @ Author : weiping liu
//
//


#if !defined(_PIPELINEPATHOLOGYVIRUSFACTORY_H)
#define _PIPELINEPATHOLOGYVIRUSFACTORY_H
//#include "PipelinePathologyVirusFactory_export.h"
#include "PipelineFactoryBase.h"

namespace ALPHA
{
	namespace VIRUS
	{
		class PipelinePathologyVirusFactory : public COMM::PipelineFactoryBase {
		public:
			explicit PipelinePathologyVirusFactory();
			~PipelinePathologyVirusFactory() override;
			std::shared_ptr<COMM::PipelineBase> createPipeline() override;
		};
	}
}

#endif  //_PIPELINEPATHOLOGYVIRUSFACTORY_H
