
#ifndef PIPELINEPATHOLOGYPDL1_EXPORT_H
#define PIPELINEPATHOLOGYPDL1_EXPORT_H

#ifdef PIPELINEPATHOLOGYPDL1_STATIC_DEFINE
#  define PIPELINEPATHOLOGYPDL1_EXPORT
#  define PIPELINEPATHOLOGYPDL1_NO_EXPORT
#else
#  ifndef PIPELINEPATHOLOGYPDL1_EXPORT
#    ifdef PipelinePathologyPDL1_EXPORTS
        /* We are building this library */
#      define PIPELINEPATHOLOGYPDL1_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define PIPELINEPATHOLOGYPDL1_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef PIPELINEPATHOLOGYPDL1_NO_EXPORT
#    define PIPELINEPATHOLOGYPDL1_NO_EXPORT 
#  endif
#endif

#ifndef PIPELINEPATHOLOGYPDL1_DEPRECATED
#  define PIPELINEPATHOLOGYPDL1_DEPRECATED __declspec(deprecated)
#endif

#ifndef PIPELINEPATHOLOGYPDL1_DEPRECATED_EXPORT
#  define PIPELINEPATHOLOGYPDL1_DEPRECATED_EXPORT PIPELINEPATHOLOGYPDL1_EXPORT PIPELINEPATHOLOGYPDL1_DEPRECATED
#endif

#ifndef PIPELINEPATHOLOGYPDL1_DEPRECATED_NO_EXPORT
#  define PIPELINEPATHOLOGYPDL1_DEPRECATED_NO_EXPORT PIPELINEPATHOLOGYPDL1_NO_EXPORT PIPELINEPATHOLOGYPDL1_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef PIPELINEPATHOLOGYPDL1_NO_DEPRECATED
#    define PIPELINEPATHOLOGYPDL1_NO_DEPRECATED
#  endif
#endif

#endif /* PIPELINEPATHOLOGYPDL1_EXPORT_H */
