//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : XS
//  @ File Name : InferLocalPathologyXS.cpp
//  @ Date : 2019/8/15
//  @ Author : weiping liu
//
//

#include <memory>
#include "DataObj.h"
#include "InferLocalPathologyXS.h"
#include <vector>

namespace ALPHA
{
	namespace XS
	{
		InferLocalPathologyXS::InferLocalPathologyXS() : COMM::InferLocalBase()
		{

		}

		InferLocalPathologyXS::~InferLocalPathologyXS()
		{

		}

		

	//**********************************************************************************************************************
		COMM::DataObj* InferLocalPathologyXS::predict(COMM::DataObj* dataObj, const std::string& modelName)
		{
			IFPipelinePathologyXSIn* input_XS = dynamic_cast<IFPipelinePathologyXSIn*>(dataObj);
			IFPipelinePathologyXSOut* output_XS(new IFPipelinePathologyXSOut());
			int cut_width = 512;
			int cut_height = 512;
			std::string config_path =  input_XS->m_config_path;
			if (input_XS->m_format_dismatch)
			{
				output_XS->format_wrong = true;
				return output_XS;
			}
			LOG4CPLUS_INFO(COMM::MyLogger::getInstance()->m_rootLog, "Start reading svs: " << input_XS->m_svs_path.c_str());

			if (!openslide_can_open(input_XS->m_svs_path.c_str())) {
				LOG4CPLUS_ERROR(COMM::MyLogger::getInstance()->m_rootLog, " Image is broken ");
				output_XS->file_broken = true;
				return output_XS;
			}


			openslide_t* slide = openslide_open(input_XS->m_svs_path.c_str());
			if (openslide_get_error(slide) != NULL)
			{
				openslide_close(slide);
				std::cout << "slide corruption" << std::endl;
				LOG4CPLUS_ERROR(COMM::MyLogger::getInstance()->m_rootLog, "Could not read slide.");
				output_XS->file_broken = true;
				return output_XS;
			}
			else
			{
				LOG4CPLUS_INFO(COMM::MyLogger::getInstance()->m_rootLog, "Load slide success.");
			}
			ALPHA::XS::IOThread io(input_XS, slide, cut_width, cut_height);
			ALPHA::XS::AIThread ai(config_path, output_XS, &io);
			io.startThread();
			ai.startThread();
			io.m_run_thread->join();
			LOG4CPLUS_INFO(COMM::MyLogger::getInstance()->m_rootLog, "Return results");
			openslide_close(slide);
			return output_XS;
		}
	}
}