
#ifndef PIPELINEPATHOLOGYUTILS_EXPORT_H
#define PIPELINEPATHOLOGYUTILS_EXPORT_H

#ifdef PIPELINEPATHOLOGYUTILS_STATIC_DEFINE
#  define PIPELINEPATHOLOGYUTILS_EXPORT
#  define PIPELINEPATHOLOGYUTILS_NO_EXPORT
#else
#  ifndef PIPELINEPATHOLOGYUTILS_EXPORT
#    ifdef PipelinePathologyUtils_EXPORTS
        /* We are building this library */
#      define PIPELINEPATHOLOGYUTILS_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define PIPELINEPATHOLOGYUTILS_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef PIPELINEPATHOLOGYUTILS_NO_EXPORT
#    define PIPELINEPATHOLOGYUTILS_NO_EXPORT 
#  endif
#endif

#ifndef PIPELINEPATHOLOGYUTILS_DEPRECATED
#  define PIPELINEPATHOLOGYUTILS_DEPRECATED __declspec(deprecated)
#endif

#ifndef PIPELINEPATHOLOGYUTILS_DEPRECATED_EXPORT
#  define PIPELINEPATHOLOGYUTILS_DEPRECATED_EXPORT PIPELINEPATHOLOGYUTILS_EXPORT PIPELINEPATHOLOGYUTILS_DEPRECATED
#endif

#ifndef PIPELINEPATHOLOGYUTILS_DEPRECATED_NO_EXPORT
#  define PIPELINEPATHOLOGYUTILS_DEPRECATED_NO_EXPORT PIPELINEPATHOLOGYUTILS_NO_EXPORT PIPELINEPATHOLOGYUTILS_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef PIPELINEPATHOLOGYUTILS_NO_DEPRECATED
#    define PIPELINEPATHOLOGYUTILS_NO_DEPRECATED
#  endif
#endif

#endif /* PIPELINEPATHOLOGYUTILS_EXPORT_H */
