
#ifndef PIPELINEPATHOLOGYXS_EXPORT_H
#define PIPELINEPATHOLOGYXS_EXPORT_H

#ifdef PIPELINEPATHOLOGYXS_STATIC_DEFINE
#  define PIPELINEPATHOLOGYXS_EXPORT
#  define PIPELINEPATHOLOGYXS_NO_EXPORT
#else
#  ifndef PIPELINEPATHOLOGYXS_EXPORT
#    ifdef PipelinePathologyXS_EXPORTS
        /* We are building this library */
#      define PIPELINEPATHOLOGYXS_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define PIPELINEPATHOLOGYXS_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef PIPELINEPATHOLOGYXS_NO_EXPORT
#    define PIPELINEPATHOLOGYXS_NO_EXPORT 
#  endif
#endif

#ifndef PIPELINEPATHOLOGYXS_DEPRECATED
#  define PIPELINEPATHOLOGYXS_DEPRECATED __declspec(deprecated)
#endif

#ifndef PIPELINEPATHOLOGYXS_DEPRECATED_EXPORT
#  define PIPELINEPATHOLOGYXS_DEPRECATED_EXPORT PIPELINEPATHOLOGYXS_EXPORT PIPELINEPATHOLOGYXS_DEPRECATED
#endif

#ifndef PIPELINEPATHOLOGYXS_DEPRECATED_NO_EXPORT
#  define PIPELINEPATHOLOGYXS_DEPRECATED_NO_EXPORT PIPELINEPATHOLOGYXS_NO_EXPORT PIPELINEPATHOLOGYXS_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef PIPELINEPATHOLOGYXS_NO_DEPRECATED
#    define PIPELINEPATHOLOGYXS_NO_DEPRECATED
#  endif
#endif

#endif /* PIPELINEPATHOLOGYXS_EXPORT_H */
