//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Pumo
//  @ File Name : DataObj.h
//  @ Date : 2019/7/3
//  @ Author : weiping liu
//
//


#if !defined(_DATAOBJ_H)
#define _DATAOBJ_H

namespace ALPHA
{
	namespace COMM
	{
		class DataObj
		{
		public:
			DataObj(){}
			virtual ~DataObj(){}
		};

	};
};

#endif  //_DATAOBJ_H
