//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Pumo
//  @ File Name : DataInferBase.h
//  @ Date : 2019/7/3
//  @ Author : weiping liu
//
//


#if !defined(_DATAINFERBASE_H)
#define _DATAINFERBASE_H

#include "DataObj.h"

namespace ALPHA
{
	namespace COMM
	{
		
		class DataInferBase : public DataObj
		{
		};

	};
};

#endif  //_DATAINFERBASE_H
