//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Pumo
//  @ File Name : IFBase.h
//  @ Date : 2019/7/5
//  @ Author : weiping liu
//
//


#if !defined(_IFBASE_H)
#define _IFBASE_H

#include <string>
#include "DataObj.h"

namespace ALPHA
{
	namespace COMM
	{
		
		class IFBase : public DataObj
		{
		public:
			IFBase():DataObj(){}
			~IFBase() override {}
			virtual void Serialization(const std::string & outPutPath = "") {}
			virtual void DeSerialization(const std::string & inPutPath = "") {}
		};

	};
};
#endif  //_IFBASE_H
