//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : common
//  @ File Name : IFPipelineImagesIn.h
//  @ Date : 2019/8/15
//  @ Author : weiping liu
//
//


#if !defined(_IFPIPELINEIMAGESIN_H)
#define _IFPIPELINEIMAGESIN_H

#include "IFBase.h"
#include <vector>
#include <string>

namespace ALPHA
{
	namespace COMM
	{
		class IFPipelineImagesIn : public IFBase
		{
		public:
			explicit IFPipelineImagesIn() :IFBase() {}
			~IFPipelineImagesIn()override {}
			inline void setImagePaths(std::vector<std::string>& vecImagePaths)
			{
				_vecImagePaths = vecImagePaths;
			}
			inline void setSeriesInstanceUIDs(std::vector<std::string>& vecSeriesInstanceUIDs)
			{
				_vecSeriesInstanceUIDs = vecSeriesInstanceUIDs;
			}
			inline std::vector<std::string> getImagePaths()
			{
				return _vecImagePaths;
			}
			inline std::vector<std::string> getSeriesInstanceUIDs()
			{
				return _vecSeriesInstanceUIDs;
			}
		private:
			std::vector<std::string> _vecSeriesInstanceUIDs;
			std::vector<std::string> _vecImagePaths;
		};
	}
}


#endif  //_IFPIPELINEIMAGESIN_H
