//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Pumo
//  @ File Name : InferBase.h
//  @ Date : 2019/7/3
//  @ Author : weiping liu
//
//


#if !defined(_INFERBASE_H)
#define _INFERBASE_H

#include <string>

namespace ALPHA
{
	namespace COMM
	{
		
		class DataObj;
		class InferBase
		{
		public:
			explicit InferBase():modelName(){}
			virtual ~InferBase(){}
			virtual DataObj* predict(DataObj* dataObj, const std::string & modelName)=0;
			inline std::string getModelName() { return modelName; }
		protected:
			//virtual void predictor(DataObj* dataObj) = 0;
			//virtual DataObj* getOutput() = 0;
			std::string modelName;
		};
	};
};
#endif  //_INFERBASE_H
