//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : common
//  @ File Name : InferLocalBase.h
//  @ Date : 2019/7/3
//  @ Author : weiping liu
//
//


#if !defined(_INFERLOCALBASE_H)
#define _INFERLOCALBASE_H

#include "InferBase.h"

namespace ALPHA
{
	namespace COMM
	{
		
		class InferLocalBase : public InferBase
		{
		public:
			explicit InferLocalBase():InferBase(){}
			~InferLocalBase() override {}
		
		};


	};
};

#endif  //_INFERLOCALBASE_H
