//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Pumo
//  @ File Name : PiplineElementAlgorithmMachineLearningBase.h
//  @ Date : 2019/7/3
//  @ Author : weiping liu
//
//


#if !defined(_PIPLINEELEMENTALGORITHMMACHINELEARNINGBASE_H)
#define _PIPLINEELEMENTALGORITHMMACHINELEARNINGBASE_H

#include <vector>
#include <memory>
#include "PipelineElementAlgorithmBase.h"

namespace ALPHA
{
	namespace COMM
	{
		
		class InferBase;

		class PipelineElementAlgorithmMachineLearningBase : public PipelineElementAlgorithmBase
		{
		public:
			explicit PipelineElementAlgorithmMachineLearningBase():PipelineElementAlgorithmBase(){}
			virtual ~PipelineElementAlgorithmMachineLearningBase(){}
			void update() override
			{
				preproc();
				infer();
				postproc();
			}
		protected:
			std::vector<std::shared_ptr<InferBase>> ptrInferBase;
			virtual void preproc() = 0;
			virtual void infer() = 0;
			virtual void postproc() = 0;
		};

	};
};

#endif  //_PIPLINEELEMENTALGORITHMMACHINELEARNINGBASE_H
