//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Pumo
//  @ File Name : PiplineElementAlgorithmBase.h
//  @ Date : 2019/7/3
//  @ Author : weiping liu
//
//


#if !defined(_PIPLINEELEMENTALGORITHMBASE_H)
#define _PIPLINEELEMENTALGORITHMBASE_H

#include "PipelineElementBase.h"

namespace ALPHA
{
	namespace COMM
	{
		
		class PipelineElementAlgorithmBase : public PipelineElementBase
		{
		public:
			explicit PipelineElementAlgorithmBase():PipelineElementBase(){}
			virtual ~PipelineElementAlgorithmBase(){}
			virtual void update() = 0;
		};

	};
};

#endif  //_PIPLINEELEMENTALGORITHMBASE_H
