//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Pumo
//  @ File Name : PipelineBase.h
//  @ Date : 2019/7/3
//  @ Author : weiping liu
//
//


#if !defined(_PIPELINEBASE_H)
#define _PIPELINEBASE_H

#include <memory>
#include "DataObj.h"

namespace ALPHA
{
	namespace COMM
	{
		
		class PipelineBase
		{
		public:
			explicit PipelineBase() {}
			virtual ~PipelineBase() {}
			virtual void setInput(std::shared_ptr<DataObj> Input) = 0;
			virtual std::shared_ptr<DataObj> getOutput() = 0;
			virtual void update() = 0;
			virtual void loadResults() {}
		};

	};
};

#endif  //_PIPELINEBASE_H
