//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Pumo
//  @ File Name : PipelineElementBase.h
//  @ Date : 2019/7/3
//  @ Author : weiping liu
//
//


#if !defined(_PIPELINEELEMENTBASE_H)
#define _PIPELINEELEMENTBASE_H

#include <memory>
#include "DataObj.h"

namespace ALPHA
{
	namespace COMM
	{
				
		class PipelineElementBase
		{
		public:
			explicit PipelineElementBase() {}
			virtual ~PipelineElementBase() {}
			virtual void setInput(std::shared_ptr< DataObj > Input) = 0;
			virtual std::shared_ptr<DataObj> getOutput() = 0;
			virtual void update() = 0;
		};

	};
};

#endif  //_PIPELINEELEMENTBASE_H
