
#ifndef PIPELINEPATHOLOGYLUNGCANCER_EXPORT_H
#define PIPELINEPATHOLOGYLUNGCANCER_EXPORT_H

#ifdef PIPELINEPATHOLOGYLUNGCANCER_STATIC_DEFINE
#  define PIPELINEPATHOLOGYLUNGCANCER_EXPORT
#  define PIPELINEPATHOLOGYLUNGCANCER_NO_EXPORT
#else
#  ifndef PIPELINEPATHOLOGYLUNGCANCER_EXPORT
#    ifdef PipelinePathologyLungCancer_EXPORTS
        /* We are building this library */
#      define PIPELINEPATHOLOGYLUNGCANCER_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define PIPELINEPATHOLOGYLUNGCANCER_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef PIPELINEPATHOLOGYLUNGCANCER_NO_EXPORT
#    define PIPELINEPATHOLOGYLUNGCANCER_NO_EXPORT 
#  endif
#endif

#ifndef PIPELINEPATHOLOGYLUNGCANCER_DEPRECATED
#  define PIPELINEPATHOLOGYLUNGCANCER_DEPRECATED __declspec(deprecated)
#endif

#ifndef PIPELINEPATHOLOGYLUNGCANCER_DEPRECATED_EXPORT
#  define PIPELINEPATHOLOGYLUNGCANCER_DEPRECATED_EXPORT PIPELINEPATHOLOGYLUNGCANCER_EXPORT PIPELINEPATHOLOGYLUNGCANCER_DEPRECATED
#endif

#ifndef PIPELINEPATHOLOGYLUNGCANCER_DEPRECATED_NO_EXPORT
#  define PIPELINEPATHOLOGYLUNGCANCER_DEPRECATED_NO_EXPORT PIPELINEPATHOLOGYLUNGCANCER_NO_EXPORT PIPELINEPATHOLOGYLUNGCANCER_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef PIPELINEPATHOLOGYLUNGCANCER_NO_DEPRECATED
#    define PIPELINEPATHOLOGYLUNGCANCER_NO_DEPRECATED
#  endif
#endif

#endif /* PIPELINEPATHOLOGYLUNGCANCER_EXPORT_H */
