
#ifndef PIPELINEPATHOLOGYTCT_EXPORT_H
#define PIPELINEPATHOLOGYTCT_EXPORT_H

#ifdef PIPELINEPATHOLOGYTCT_STATIC_DEFINE
#  define PIPELINEPATHOLOGYTCT_EXPORT
#  define PIPELINEPATHOLOGYTCT_NO_EXPORT
#else
#  ifndef PIPELINEPATHOLOGYTCT_EXPORT
#    ifdef PipelinePathologyTCT_EXPORTS
        /* We are building this library */
#      define PIPELINEPATHOLOGYTCT_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define PIPELINEPATHOLOGYTCT_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef PIPELINEPATHOLOGYTCT_NO_EXPORT
#    define PIPELINEPATHOLOGYTCT_NO_EXPORT 
#  endif
#endif

#ifndef PIPELINEPATHOLOGYTCT_DEPRECATED
#  define PIPELINEPATHOLOGYTCT_DEPRECATED __declspec(deprecated)
#endif

#ifndef PIPELINEPATHOLOGYTCT_DEPRECATED_EXPORT
#  define PIPELINEPATHOLOGYTCT_DEPRECATED_EXPORT PIPELINEPATHOLOGYTCT_EXPORT PIPELINEPATHOLOGYTCT_DEPRECATED
#endif

#ifndef PIPELINEPATHOLOGYTCT_DEPRECATED_NO_EXPORT
#  define PIPELINEPATHOLOGYTCT_DEPRECATED_NO_EXPORT PIPELINEPATHOLOGYTCT_NO_EXPORT PIPELINEPATHOLOGYTCT_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef PIPELINEPATHOLOGYTCT_NO_DEPRECATED
#    define PIPELINEPATHOLOGYTCT_NO_DEPRECATED
#  endif
#endif

#endif /* PIPELINEPATHOLOGYTCT_EXPORT_H */
